// Bulgarian districts/cities for job location selection
export const DISTRICTS = [
  'Sofia',
  'Plovdiv',
  'Varna',
  'Burgas',
  'Ruse',
  'Stara Zagora',
  'Pleven',
  'Sliven',
  'Dobrich',
  'Shumen',
  'Pernik',
  'Yambol',
  'Haskovo',
  'Pazardzhik',
  'Blagoevgrad',
  'Veliko Tarnovo',
  'Vratsa',
  'Gabrovo',
  'Asenovgrad',
  'Kardzhali',
  'Kyustendil',
  'Lovech',
  'Montana',
  'Razgrad',
  'Silistra',
  'Targovishte',
  'Smolyan',
  'Svishtov',
  'Dupnitsa',
  'Gorna Oryahovitsa',
] as const;

export type District = typeof DISTRICTS[number];
